#en:
#  languageCode: en
#  languageName: English
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  # contentDir: content/en

# Uncomment for multilingual sites, and customize the following config.
zh:
  languageCode: zh
  languageName: 简体中文
<<<<<<< HEAD
    #  contentDir: content/zh
  title: SlothBlog
=======
  contentDir: content/zh
  title: 怠惰博客
>>>>>>> 996081a (重新配置)
