#en:
#  languageCode: en
#  languageName: English
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  # contentDir: content/en

zh:
   languageCode: zh
   languageName: 简体中文
   contentDir: content/zh
   title: 怠惰博客
